apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongodb
 namespace: roboshop
 labels: # these labels belong to deployment
  environment: dev
  project: roboshop
  tier: db
spec:
 replicas: 1
 selector:
  matchLabels: # these labels should match with pod
   environment: dev
   project: roboshop
   tier: db
 template:
  metadata:
   environment: dev
   project: roboshop
   tier: db
  spec:
   containers:
    - name: mongodb
      image: sivadevops1014/mongodb:1.0.0
---
apiVersion: v1
kind: Service
metadata:
 name: mongodb
 namespace: roboshop
spec:
 type: ClusterIP
 selector:
  environment: dev
  project: roboshop
  tier: db
 ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017 # this port belongs to service
    targetPort: 27017 # this port belongs to container

