apiVersion: apps/v1
kind: Deployment
metadata:
 name: catalogue
 namespace: roboshop 
 labels: # these labels belong to deployment
  environment: dev
  tier: app
  project: roboshop
spec:
 replicas: 1
 selector:
  matchLabels: # these labels should match with pod
   environment: dev
   tier: app
   project: roboshop
 template: # this is the pod definition
  metadata:
   labels:
    environment: dev
    tier: app
    project: roboshop
  spec:
   containers:
    - name: catalogue
      image: sivadevops1014/catalogue:1.1.0
---
apiVersion: v1
kind: Service
metadata:
 name: catalogue
 namespace: roboshop
spec:
 type: ClusterIP
 selector: 
  environment: dev
  tier: app
  project: roboshop
 ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080 # this port belongs to service
    targetPort: 8080 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: catalogue
 namespace: roboshop
data:
 MONGO: "true" # keep true in double quotes
 MONGO_URL: "mongodb://mongodb:27017/catalogue"  #protocol://servicename-serviceport/schema