apiVersion: apps/v1
kind: Deployment
metadata:
 name: user
 namespace: roboshop
 labels:
  environment: dev
  app: user
  tier: app
spec:
 replicas: 1
 selector:
  matchLabels:
   environment: dev
   app: user
   tier: app
 template:
  metadata:
   labels:
    environment: dev
    app: user
    tier: app
  spec:
   containers:
    - name: user
      image: sivadevops1014/user:1.1.0
      envFrom:
       - configMapRef:
          name: user
---
apiVersion: v1
kind: Service
metadata:
 name: user
 namespace: user
spec:
 type: Cluster IP
 selector:
  environment: dev
  app: user
  tier: app
 ports:
  - name: user-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: user
data:
 REDIS_HOST: "redis"
 MONGO_URL: "mongodb://mongodb:27017/users"
