apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis
 namespace: roboshop
 labels:
  environment: dev
  tier: db
  app: redis
spec:
 replicas: 1
 selector:
  matchLabels:
   environment: dev
   tier: db
   app: redis
 template:
  metadata:
   labels:
    environment: dev
    tier: db
    app: redis
  spec:
   containers:
    - name: redis
      image: redis
---
apiVersion: v1
kind: Service
metadata:
 name: redis
 namespace: roboshop
spec:
 type: ClusterIP
 selector:
  environment: dev
  tier: db
  app: redis
 ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379  